flowchart TD
%% generated in 0.06s
    examples__agent_broker["examples.agent-broker<br/>2 funcs"]
    examples__ci_agent["examples.ci-agent<br/>2 funcs"]
    examples__common["examples.common<br/>13 funcs"]
    examples__control_plane["examples.control-plane<br/>5 funcs"]
    examples__control_plugin["examples.control-plugin<br/>10 funcs"]
    examples__headless_virtual["examples.headless-virtual<br/>2 funcs"]
    examples__host_mirror["examples.host-mirror<br/>3 funcs"]
    examples__host_relay["examples.host-relay<br/>4 funcs"]
    packages__cli2vdisplay["packages.cli2vdisplay<br/>1 funcs"]
    packages__dsl2vdisplay["packages.dsl2vdisplay<br/>57 funcs"]
    packages__mcp2vdisplay["packages.mcp2vdisplay<br/>3 funcs"]
    packages__nlp2vdisplay["packages.nlp2vdisplay<br/>3 funcs"]
    packages__rest2vdisplay["packages.rest2vdisplay<br/>2 funcs"]
    packages__uri2vdisplay["packages.uri2vdisplay<br/>2 funcs"]
    packages__vdisplay_agent["packages.vdisplay-agent<br/>129 funcs"]
    src__vdisplay["src.vdisplay<br/>982 funcs"]
    packages__vdisplay_agent ==>|28| src__vdisplay
    packages__dsl2vdisplay ==>|6| src__vdisplay
    src__vdisplay ==>|6| packages__dsl2vdisplay
    packages__mcp2vdisplay ==>|4| src__vdisplay
    packages__rest2vdisplay ==>|4| packages__dsl2vdisplay
    src__vdisplay ==>|4| packages__vdisplay_agent
    examples__host_mirror -->|3| src__vdisplay
    examples__host_mirror -->|3| examples__common
    examples__host_relay -->|3| src__vdisplay
    examples__host_relay -->|3| examples__common
    packages__mcp2vdisplay -->|2| packages__dsl2vdisplay
    packages__cli2vdisplay -->|2| packages__dsl2vdisplay
    packages__rest2vdisplay -->|2| src__vdisplay
    examples__headless_virtual -->|2| examples__common
    examples__ci_agent -->|2| examples__common
    packages__mcp2vdisplay -->|1| packages__nlp2vdisplay
    packages__uri2vdisplay -->|1| packages__dsl2vdisplay
    packages__nlp2vdisplay -->|1| src__vdisplay
    packages__vdisplay_agent -->|1| packages__rest2vdisplay
    examples__control_plugin -->|1| src__vdisplay
    examples__control_plane -->|1| src__vdisplay
    examples__agent_broker -->|1| src__vdisplay
    examples__common -->|1| src__vdisplay
    src__vdisplay -->|1| packages__rest2vdisplay
    src__vdisplay -->|1| examples__control_plugin
